apiVersion: v1
kind: ConfigMap
metadata:
  name: altea-pay-config
  namespace: altea-pay
data:
  NEXTAUTH_URL: "https://app.alteapay.com"
  NEXT_PUBLIC_APP_URL: "https://app.alteapay.com"
  ASSERTIVA_BASE_URL: "https://api.assertivasolucoes.com.br"
  NODE_ENV: "production"
  PORT: "3000"
