apiVersion: v1
kind: Service
metadata:
  name: altea-pay
  namespace: altea-pay
spec:
  selector:
    app: altea-pay
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
